#!/bin/bash
set -x

#glib-> libffi
#gtk3 ->glib gdk_pixbuf harfbuzz fontconfig
#update-mime-database-> gcc 
for paket in libffi fribidi freetype atkmm libepoxy glib fontconfig \gcc gdk-pixbuf harfbuzz shadow openbox gtk3 libjpeg-turbo dbus polkit elogind shared-mime-info
do
/bin/bps -i $paket;
done

